name: timewise_dtu
description: A smart timetable app for DTU students

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.2
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  uuid: ^4.5.1
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/timewise_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/timewise_icon.png

